name: CI/CD with SonarQube and Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # - name: SonarQube Scan
      #   uses: sonarsource/sonarqube-scan-action@v1.3
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Build Docker Image
        run: |
          docker build -t my-app .

      - name: Push Docker Image to Minikube
        run: |
          eval $(minikube docker-env)
          docker tag my-app my-app:latest
          docker push my-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Start Minikube
        run: |
          minikube start
          eval $(minikube docker-env)

      - name: Set Kubeconfig
        run: |
          mkdir -p ~/.kube
          cp $(minikube kubectl -- get kubeconfig) ~/.kube/config

      - name: Verify Kubernetes connection
        run: kubectl cluster-info

      - name: Deploy to Minikube
        run: |
          kubectl apply -f kubernetes.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods
